"""0003 audit metadata

Revision ID: 21dd6fad4d4b
Revises: 4f210d31ac14
Create Date: 2026-06-06 03:33:02.342050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '21dd6fad4d4b'
down_revision: Union[str, None] = '4f210d31ac14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_events', 'metadata')
    # ### end Alembic commands ###
