"""0002 user capabilities

Revision ID: 4f210d31ac14
Revises: ecadcc21a6b6
Create Date: 2026-06-06 00:27:35.836095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4f210d31ac14'
down_revision: Union[str, None] = 'ecadcc21a6b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'capabilities')
    # ### end Alembic commands ###
