"""0004 evidence validity_state

Revision ID: 743fb161b5cc
Revises: 21dd6fad4d4b
Create Date: 2026-06-06 03:42:37.881298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '743fb161b5cc'
down_revision: Union[str, None] = '21dd6fad4d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evidence_items', sa.Column('validity_state', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_items', 'validity_state')
    # ### end Alembic commands ###
