"""0006 control_hash

Revision ID: d19735c24495
Revises: 9cdacc9c79fe
Create Date: 2026-06-06 04:16:49.705891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd19735c24495'
down_revision: Union[str, None] = '9cdacc9c79fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_results', sa.Column('control_hash', sa.String(length=64), nullable=True))
    op.add_column('controls', sa.Column('control_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controls', 'control_hash')
    op.drop_column('assessment_results', 'control_hash')
    # ### end Alembic commands ###
