"""0001 initial schema

Revision ID: ecadcc21a6b6
Revises: 
Create Date: 2026-06-05 23:38:34.373255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ecadcc21a6b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('id')
    )
    op.create_table('controls',
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('frameworks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('article_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('annex_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('catalog_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('control_id', 'version')
    )
    op.create_table('frameworks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('version', sa.String(length=128), nullable=False),
    sa.Column('jurisdiction', sa.String(length=64), nullable=False),
    sa.Column('catalog_version', sa.String(length=32), nullable=False),
    sa.Column('effective_date', sa.String(length=32), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_systems',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('intended_purpose', sa.Text(), nullable=False),
    sa.Column('deployment_context', sa.String(length=64), nullable=False),
    sa.Column('risk_tier', sa.String(length=32), nullable=True),
    sa.Column('annex_iii_category', sa.String(length=64), nullable=True),
    sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_systems_org_id'), 'ai_systems', ['org_id'], unique=False)
    op.create_table('evidence_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('control_version', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('freshness_seconds', sa.Integer(), nullable=True),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['control_id', 'control_version'], ['controls.control_id', 'controls.version'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('framework_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('article_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applies_to', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('catalog_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('catalog_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_org_id'), 'assessments', ['org_id'], unique=False)
    op.create_index(op.f('ix_assessments_system_id'), 'assessments', ['system_id'], unique=False)
    op.create_table('control_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('control_version', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['control_id', 'control_version'], ['controls.control_id', 'controls.version'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('control_id', 'control_version', 'requirement_id', name='uq_control_requirement')
    )
    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('system_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('field', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('supersedes', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['supersedes'], ['evidence_items.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['ai_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_control_id'), 'evidence_items', ['control_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_org_id'), 'evidence_items', ['org_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_system_id'), 'evidence_items', ['system_id'], unique=False)
    op.create_table('assessment_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=64), nullable=False),
    sa.Column('control_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('freshness_grade', sa.String(length=1), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('missing_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_results_assessment_id'), 'assessment_results', ['assessment_id'], unique=False)
    # ### end Alembic commands ###

    # Append-only enforcement for the audit ledger and evidence store.
    # A REVOKE would not bind the table owner (the app role owns these tables),
    # so a BEFORE UPDATE OR DELETE trigger is used — it raises regardless of role.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION comply_block_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'append-only table: % not allowed on %', TG_OP, TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for tbl in ("audit_events", "evidence_items"):
        op.execute(
            f"""
            CREATE TRIGGER {tbl}_append_only
            BEFORE UPDATE OR DELETE ON {tbl}
            FOR EACH ROW EXECUTE FUNCTION comply_block_mutation();
            """
        )


def downgrade() -> None:
    # Triggers drop with their tables; the shared function must be dropped explicitly.
    op.execute("DROP FUNCTION IF EXISTS comply_block_mutation() CASCADE;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assessment_results_assessment_id'), table_name='assessment_results')
    op.drop_table('assessment_results')
    op.drop_index(op.f('ix_evidence_items_system_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_org_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_control_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_table('control_requirements')
    op.drop_index(op.f('ix_assessments_system_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_org_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('requirements')
    op.drop_table('evidence_requirements')
    op.drop_index(op.f('ix_ai_systems_org_id'), table_name='ai_systems')
    op.drop_table('ai_systems')
    op.drop_table('organizations')
    op.drop_table('frameworks')
    op.drop_table('controls')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
